name: "Create Release"
description: ""
runs:
  using: "composite"
  steps:
    - name: Build Release
      shell: bash
      run: |
        cargo build --release
        mkdir -p artifacts/builds
        find . -maxdepth 1 -type f \( -name "public-app" -o -name "public-app.exe" \) -exec cp {} artifacts/builds/ \;
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ runner.os }}
        path: artifacts/builds/*
