name: "Create Release"
description: ""
runs:
  using: "composite"
  steps:
    - name: Build Release
      shell: bash
      run: |
        cargo build --release
        mkdir -p artifacts/builds
        cp target/release/public-app.{,exe} artifacts/builds/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ runner.os }}
        path: artifacts/builds/*
